export const Users = [
    {
      id:1,
      profilePicture: "/images/connect-spirit.png",
      username: "Connect Magazine",
      hashtag: "#SpiritofSafaricom",
    },
    {
      id:2,
      profilePicture: "/images/connect-spirit.png",
      username: "Connect Magazine",
      hashtag: "#SpiritofSafaricom",
    },
    {
      id:3,
      profilePicture: "/images/connect-spirit.png",
      username: "Connect Magazine",
      hashtag: "#SpiritofSafaricom",
    },
    {
      id:4,
      profilePicture: "/images/connect-spirit.png",
      username: "Connect Magazine",
      hashtag: "#SpiritofSafaricom",
    },
    {
      id:5,
      profilePicture: "/images/connect-spirit.png",
      username: "Connect Magazine",
      hashtag: "#SpiritofSafaricom",
    },
    {
      id:6,
      profilePicture: "/images/connect-spirit.png",
      username: "Connect Magazine",
      hashtag: "#SpiritofSafaricom",
    },
    {
      id:7,
      profilePicture: "/images/connect-spirit.png",
      username: "Connect Magazine",
      hashtag: "#SpiritofSafaricom",
    },
    {
      id:8,
      profilePicture: "/images/connect-spirit.png",
      username: "Connect Magazine",
      hashtag: "#SpiritofSafaricom",
    },
    {
      id:9,
      profilePicture: "/images/connect-spirit.png",
      username: "Connect Magazine",
      hashtag: "#SpiritofSafaricom",
    },
    {
      id:10,
      profilePicture: "/images/connect-spirit.png",
      username: "Connect Magazine",
      hashtag: "#SpiritofSafaricom",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Safaricom Spirit is defined by our Purpose, Customer Obsession, Innovation and Collaboration. Our Purpose drives us as an organization, Customer Obsession inspires us to stay true to our brand promise, Innovation encourages curiosity, reinvention and re-skilling ourselves, while Collaboration motivates us to work together to achieve great things. In this edition...",
      photo: "/images/banners/spirit-of-safaricom.jpg",
      date: "27 Sep, 2021",
      userId: 1,
      like: 129,
      comment: 9,
    },
    {
      id: 2,
      desc: "Leran something new today!",
      photo: "/images/banners/fintech-banner.jpg",
      date: "10 Sep, 2021",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "images/banners/video-banner-01.jpg",
      date: "01 Aug, 2021",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      desc: "Get to know Kris Senanu. Learn what Kris Senanu has to say about the impact of the Agile journey, as he discusses the emotional attribute that forms our culture of safety and sustainability and lets us in on his social preferences, love for local jams and mud fun on the off-road. Watch, like and leave a comment on your take of the journey. #GetToKnow",
      photo: "images/banners/video-banner-02.jpg",
      date: "27 Sep, 2021",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      desc: "The HRBP offers a guiding voice towards motivating and enabling a purpose-led work life environment by upholding privacy and trust in career conversations. Find out how to collaborate with and get the support of Human Resource in staying purpose-led through embracing the right work elements within your role, as directed by June Obonyo #HRCorner...",
      photo: "images/banners/video-banner-03.jpg",
      date: "27 Sep, 2021",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      desc: "Kevin talks about his passion for doing and learning as much as he can when it comes to facilitating more customer-driven solutions. Listen to his work as a data scientist for Mtandao DIY and give your feedback on the comments #SpiritOfSafaricomHeroes...",
      photo: "images/banners/otieno-banner.jpg",
      date: "27 Sep, 2021",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "What’s happening around Safaricom #WordOnTheStreets",
      photo: "images/banners/tuko-banner.jpg",
      date: "27 Sep, 2021",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      desc: "What’s happening around Safaricom #OnSocial",
      photo: "images/banners/video-banner-04.jpg",
      date: "27 Sep, 2021",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Never a dull day at Safaricom #JustForLaughs",
      photo: "images/banners/lab-banner.jpg",
      date: "27 Sep, 2021",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      desc: "Ingredients or the Flavored Butter: 1 cup (2 sticks or 226 grams) unsalted butter, softened 2 Tbsp olive oil (not extra virgin), plus more to drizzle the top 4 Tbsp fresh lemon juice (from 1 large lemon), plus 1/2 Tbsp lemon zest 3 large garlic cloves #What’sCooking...",
      photo: "images/banners/recipe-banner.jpg",
      date: "27 Sep, 2021",
      userId: 9,
      like: 11,
      comment: 2,
    },
  ];